#++++++++++++++++++++++++++++++++++++++
# Redis Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   redis - official Redis
#           https://registry.hub.docker.com/u/library/redis/
#
#++++++++++++++++++++++++++++++++++++++

FROM redis