#++++++++++++++++++++++++++++++++++++++
# PostgreSQL Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   postgres - official PostgreSQL
#              https://registry.hub.docker.com/u/library/postgres/
#
#++++++++++++++++++++++++++++++++++++++

FROM postgres:9.4
