#++++++++++++++++++++++++++++++++++++++
# Elasticsearch Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   elasticsearch - official Elasticsaerch
#                   https://registry.hub.docker.com/u/library/elasticsearch/
#
#++++++++++++++++++++++++++++++++++++++

FROM elasticsearch
