#++++++++++++++++++++++++++++++++++++++
# Mailcatcher Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Images:
#
#   schickling/mailcatcher
#       https://registry.hub.docker.com/u/schickling/mailcatcher/
#
#++++++++++++++++++++++++++++++++++++++

FROM schickling/mailcatcher
