#++++++++++++++++++++++++++++++++++++++
# Memcached Docker container
#++++++++++++++++++++++++++++++++++++++
#
# Official images:
#
#   memcached - official Memcached
#               https://registry.hub.docker.com/u/library/memcached/
#
#++++++++++++++++++++++++++++++++++++++

FROM memcached